"""create member_contributions table

Revision ID: 3b69cf850a8d
Revises: ce1e4be99fea
Create Date: 2026-03-20 17:22:56.223525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b69cf850a8d'
down_revision: Union[str, Sequence[str], None] = 'ce1e4be99fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_contributions',
    sa.Column('member_contribution_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('contribution_amount', sa.Integer(), nullable=False),
    sa.Column('contribution_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('member_contribution_id')
    )
    op.create_index(op.f('ix_member_contributions_member_contribution_id'), 'member_contributions', ['member_contribution_id'], unique=False)
    op.drop_index(op.f('ix_simulation_runs_scenario_name'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_simulation_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_user_profiles_profile_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('policies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('policy_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=140), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('annual_interest_rate', mysql.FLOAT(), nullable=False),
    sa.Column('repayment_period_months', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('late_penalty_rate', mysql.FLOAT(), nullable=False),
    sa.Column('minimum_monthly_contribution', mysql.FLOAT(), nullable=False),
    sa.Column('grace_period_days', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('policy_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_profiles',
    sa.Column('profile_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cooperative_name', mysql.VARCHAR(length=180), nullable=False),
    sa.Column('admin_name', mysql.VARCHAR(length=140), nullable=False),
    sa.Column('admin_email', mysql.VARCHAR(length=180), nullable=False),
    sa.Column('role_title', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=140), nullable=True),
    sa.Column('bio', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('profile_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_profiles_profile_id'), 'user_profiles', ['profile_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('simulation_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scenario_name', mysql.VARCHAR(length=140), nullable=False),
    sa.Column('scenario_description', mysql.TEXT(), nullable=True),
    sa.Column('policy_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_months', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expected_new_loans', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_loan_amount', mysql.FLOAT(), nullable=False),
    sa.Column('baseline_default_rate', mysql.FLOAT(), nullable=False),
    sa.Column('economic_stress_factor', mysql.FLOAT(), nullable=False),
    sa.Column('participation_elasticity', mysql.FLOAT(), nullable=False),
    sa.Column('projected_default_rate', mysql.FLOAT(), nullable=False),
    sa.Column('projected_repayment_rate', mysql.FLOAT(), nullable=False),
    sa.Column('liquidity_index', mysql.FLOAT(), nullable=False),
    sa.Column('member_satisfaction_index', mysql.FLOAT(), nullable=False),
    sa.Column('participation_rate', mysql.FLOAT(), nullable=False),
    sa.Column('sustainability_score', mysql.FLOAT(), nullable=False),
    sa.Column('portfolio_disbursed', mysql.FLOAT(), nullable=False),
    sa.Column('portfolio_at_risk', mysql.FLOAT(), nullable=False),
    sa.Column('expected_penalty_income', mysql.FLOAT(), nullable=False),
    sa.Column('expected_contribution_inflow', mysql.FLOAT(), nullable=False),
    sa.Column('risk_flags', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], name=op.f('simulation_runs_ibfk_1')),
    sa.PrimaryKeyConstraint('simulation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_simulation_runs_simulation_id'), 'simulation_runs', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_scenario_name'), 'simulation_runs', ['scenario_name'], unique=False)
    op.drop_index(op.f('ix_member_contributions_member_contribution_id'), table_name='member_contributions')
    op.drop_table('member_contributions')
    # ### end Alembic commands ###
