"""create member_contributions table

Revision ID: 47d40c268e0f
Revises: ea1abc8d0174
Create Date: 2026-04-15 15:10:33.443797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d40c268e0f'
down_revision: Union[str, Sequence[str], None] = 'ea1abc8d0174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_contributions',
    sa.Column('member_contribution_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('contribution_amount', sa.Integer(), nullable=False),
    sa.Column('contribution_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ),
    sa.PrimaryKeyConstraint('member_contribution_id')
    )
    op.create_index(op.f('ix_member_contributions_member_contribution_id'), 'member_contributions', ['member_contribution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_contributions_member_contribution_id'), table_name='member_contributions')
    op.drop_table('member_contributions')
    # ### end Alembic commands ###
