"""add cooperative_id to members

Revision ID: 483d49c7d249
Revises: 97f7955a9023
Create Date: 2026-03-30 22:01:31.186319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483d49c7d249'
down_revision: Union[str, Sequence[str], None] = '97f7955a9023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooperatives',
    sa.Column('cooperative_id', sa.Integer(), nullable=False),
    sa.Column('cooperative_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('cooperative_id'),
    sa.UniqueConstraint('cooperative_name')
    )
    op.create_index(op.f('ix_cooperatives_cooperative_id'), 'cooperatives', ['cooperative_id'], unique=False)
    op.add_column('members', sa.Column('cooperative_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'members', 'cooperatives', ['cooperative_id'], ['cooperative_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'cooperative_id')
    op.drop_index(op.f('ix_cooperatives_cooperative_id'), table_name='cooperatives')
    op.drop_table('cooperatives')
    # ### end Alembic commands ###
