"""add new column to members

Revision ID: 524aefa99161
Revises: 2ee79f847df3
Create Date: 2026-03-07 11:42:37.368910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524aefa99161'
down_revision: Union[str, Sequence[str], None] = '2ee79f847df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('password', sa.String(length=256), nullable=False))
    op.add_column('members', sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='memberrole', native_enum=False), nullable=False))
    op.drop_index(op.f('ix_members_first_name'), table_name='members')
    op.drop_index(op.f('ix_members_last_name'), table_name='members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_members_last_name'), 'members', ['last_name'], unique=False)
    op.create_index(op.f('ix_members_first_name'), 'members', ['first_name'], unique=False)
    op.drop_column('members', 'role')
    op.drop_column('members', 'password')
    # ### end Alembic commands ###
