"""add new column in loan model

Revision ID: 7e7fd022c754
Revises: d3d8575bf1e6
Create Date: 2026-04-04 11:13:32.151784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7fd022c754'
down_revision: Union[str, Sequence[str], None] = 'd3d8575bf1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('interest_payable', sa.Float(), nullable=False))
    op.add_column('loans', sa.Column('repayment_amount', sa.Float(), nullable=False))
    op.add_column('loans', sa.Column('amount_paid', sa.Float(), nullable=False))
    op.add_column('loans', sa.Column('loan_balance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'loan_balance')
    op.drop_column('loans', 'amount_paid')
    op.drop_column('loans', 'repayment_amount')
    op.drop_column('loans', 'interest_payable')
    # ### end Alembic commands ###
