"""Add amount_paid to Penalty

Revision ID: 9bf0e77dafc8
Revises: adddddc4fd22
Create Date: 2026-05-14 18:05:49.817561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf0e77dafc8'
down_revision: Union[str, Sequence[str], None] = 'adddddc4fd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penalties', sa.Column('amount_paid', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penalties', 'amount_paid')
    # ### end Alembic commands ###
