"""create penalties table

Revision ID: adddddc4fd22
Revises: 1b9f9d2d6a10
Create Date: 2026-05-14 10:31:53.478907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'adddddc4fd22'
down_revision: Union[str, Sequence[str], None] = '1b9f9d2d6a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalties',
    sa.Column('penalty_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', name='penaltystatus', native_enum=False), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('penalty_id')
    )
    op.create_index(op.f('ix_penalties_penalty_id'), 'penalties', ['penalty_id'], unique=False)
    op.alter_column('loans', 'policy_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'policy_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_penalties_penalty_id'), table_name='penalties')
    op.drop_table('penalties')
    # ### end Alembic commands ###
