"""added new columns

Revision ID: be6ce37736e9
Revises: 7e7fd022c754
Create Date: 2026-04-13 16:46:55.093634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be6ce37736e9'
down_revision: Union[str, Sequence[str], None] = '7e7fd022c754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('policy_description', sa.String(length=255), nullable=True))
    op.add_column('policies', sa.Column('contribution_amount', sa.Float(), nullable=False))
    op.drop_column('policies', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('status', mysql.ENUM('active', 'inactive'), nullable=True))
    op.drop_column('policies', 'contribution_amount')
    op.drop_column('policies', 'policy_description')
    # ### end Alembic commands ###
