"""add new column to members

Revision ID: ce1e4be99fea
Revises: 524aefa99161
Create Date: 2026-03-15 17:25:24.084126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1e4be99fea'
down_revision: Union[str, Sequence[str], None] = '524aefa99161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('phone_number', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'phone_number')
    # ### end Alembic commands ###
