"""add_member_id_to_payments

Revision ID: d3d8575bf1e6
Revises: 483d49c7d249
Create Date: 2026-04-04 10:52:33.135493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d8575bf1e6'
down_revision: Union[str, Sequence[str], None] = '483d49c7d249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('member_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payments', 'members', ['member_id'], ['member_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'member_id')
    # ### end Alembic commands ###
