"""create scenario table

Revision ID: d4dc35c72b80
Revises: be6ce37736e9
Create Date: 2026-04-13 17:39:26.549534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4dc35c72b80'
down_revision: Union[str, Sequence[str], None] = 'be6ce37736e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('scenario_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_scenarios_scenario_id'), 'scenarios', ['scenario_id'], unique=False)
    op.add_column('policies', sa.Column('cooperative_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'policies', 'cooperatives', ['cooperative_id'], ['cooperative_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'cooperative_id')
    op.drop_index(op.f('ix_scenarios_scenario_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
