"""create policies table

Revision ID: ea1abc8d0174
Revises: d4dc35c72b80
Create Date: 2026-04-15 13:34:49.420328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea1abc8d0174'
down_revision: Union[str, Sequence[str], None] = 'd4dc35c72b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('cooperative_id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('policy_description', sa.String(length=255), nullable=True),
    sa.Column('contribution_amount', sa.Float(), nullable=False),
    sa.Column('min_shares', sa.Integer(), nullable=False),
    sa.Column('max_shares', sa.Integer(), nullable=False),
    sa.Column('loan_multiplier', sa.Float(), nullable=False),
    sa.Column('max_loan_amount', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('repayment_period', sa.Integer(), nullable=False),
    sa.Column('penalty_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.cooperative_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_policies_policy_id'), 'policies', ['policy_id'], unique=False)
    op.drop_index(op.f('ix_policies_policy_id'), table_name='policies_backup')
    op.drop_table('policies_backup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies_backup',
    sa.Column('policy_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('policy_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('interest_rate', mysql.FLOAT(), nullable=False),
    sa.Column('max_loan_amount', mysql.FLOAT(), nullable=False),
    sa.Column('repayment_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('penalty_rate', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('policy_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contribution_amount', mysql.FLOAT(), nullable=False),
    sa.Column('cooperative_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.cooperative_id'], name=op.f('policies_backup_ibfk_1')),
    sa.PrimaryKeyConstraint('policy_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_policies_policy_id'), 'policies_backup', ['policy_id'], unique=False)
    op.drop_index(op.f('ix_policies_policy_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
