"""initial migration

Revision ID: f5afbcb3e18c
Revises: 
Create Date: 2026-03-30 21:17:37.362557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5afbcb3e18c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('phone_number', sa.String(length=256), nullable=True),
    sa.Column('coopeerative_name', sa.String(length=256), nullable=True),
    sa.Column('member_status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='memberstatus', native_enum=False), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='memberrole', native_enum=False), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_index(op.f('ix_members_member_id'), 'members', ['member_id'], unique=False)
    op.create_table('policies',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('max_loan_amount', sa.Float(), nullable=False),
    sa.Column('repayment_period', sa.Integer(), nullable=False),
    sa.Column('penalty_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='policystatus'), nullable=True),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_policies_policy_id'), 'policies', ['policy_id'], unique=False)
    op.create_table('loans',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('repayment_period', sa.Integer(), nullable=False),
    sa.Column('loan_status', sa.Enum('pending', 'approved', 'active', 'completed', name='loanstatus'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_index(op.f('ix_loans_loan_id'), 'loans', ['loan_id'], unique=False)
    op.create_table('member_contributions',
    sa.Column('member_contribution_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('contribution_amount', sa.Integer(), nullable=False),
    sa.Column('contribution_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('member_contribution_id')
    )
    op.create_index(op.f('ix_member_contributions_member_contribution_id'), 'member_contributions', ['member_contribution_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.loan_id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_member_contributions_member_contribution_id'), table_name='member_contributions')
    op.drop_table('member_contributions')
    op.drop_index(op.f('ix_loans_loan_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_policies_policy_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_members_member_id'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
